export const SQL_MARKETING_TEMPLATE = {
  slug: "sql-marketing", topic: "SQL para Marketing", goal: "Dominar SQL para analisis de campanas y segmentacion en LATAM",
  language: "es", estimatedHours: 3.5,
  modules: [
    {
      id: "M1", title: "Fundamentos SELECT",
      summary: "Casos reales de campanas LATAM para dominar SELECT, WHERE, ORDER BY y DISTINCT.",
      lessons: [
        {
          id: "L1-1",
          title: "SELECT basico",
          summary: "Explorar tablas de leads LATAM para identificar columnas criticas.",
          objective: "Dominar SELECT y FROM para extraer datos base de campanas LATAM.",
          type: "video+quiz", durationMinutes: 7,
        },
        {
          id: "L1-2",
          title: "Filtros WHERE",
          summary: "Aplicar filtros LATAM por fechas, localidades y segmentos clave.",
          objective: "Configurar WHERE con operadores logicos para audiencias LATAM.",
          type: "video+quiz", durationMinutes: 7,
        },
        {
          id: "L1-3",
          title: "ORDER BY y LIMIT",
          summary: "Ordenar rankings LATAM por CTR, presupuesto y alcance.",
          objective: "Priorizar campanas LATAM ajustando ORDER BY y LIMIT.",
          type: "video+quiz", durationMinutes: 7,
        },
        {
          id: "L1-4",
          title: "DISTINCT y NULL",
          summary: "Limpiar duplicados y nulos comunes en CRMs LATAM.",
          objective: "Detectar clientes unicos y datos faltantes en contextos LATAM.",
          type: "video+quiz", durationMinutes: 7,
        },
      ],
    },
    {
      id: "M2", title: "JOINs",
      summary: "Unir fuentes de CRM y Ads LATAM con estrategias de JOIN practicas.",
      lessons: [
        {
          id: "L2-1",
          title: "Concepto de relaciones",
          summary: "Disenar modelos relacionales para funnels LATAM multicanal.",
          objective: "Entender claves primarias y foraneas en ecosistemas LATAM.",
          type: "caso-practico", durationMinutes: 7,
        },
        {
          id: "L2-2",
          title: "INNER JOIN",
          summary: "Cruzar leads activos con inversiones LATAM en ejecucion.",
          objective: "Evaluar performance LATAM integrando datos con INNER JOIN.",
          type: "caso-practico", durationMinutes: 7,
        },
        {
          id: "L2-3",
          title: "LEFT JOIN",
          summary: "Detectar leads sin follow-up en pipelines LATAM.",
          objective: "Identificar oportunidades LATAM con LEFT JOIN y valores nulos.",
          type: "caso-practico", durationMinutes: 7,
        },
        {
          id: "L2-4",
          title: "Casos de uso marketing",
          summary: "Integrar CRM, pagos y ads LATAM en reportes ejecutivos.",
          objective: "Construir paneles LATAM combinando multiples JOINs.",
          type: "caso-practico", durationMinutes: 7,
        },
      ],
    },
    {
      id: "M3", title: "Agregaciones",
      summary: "Calcular KPIs LATAM con COUNT, SUM, AVG, MIN, MAX, GROUP BY y HAVING.",
      lessons: [
        {
          id: "L3-1",
          title: "COUNT y SUM",
          summary: "Medir volumen de leads y gasto LATAM con agregaciones basicas.",
          objective: "Construir tableros LATAM que consoliden inversiones y resultados.",
          type: "taller", durationMinutes: 7,
        },
        {
          id: "L3-2",
          title: "AVG, MIN, MAX",
          summary: "Comparar retornos LATAM promedio y extremos por segmento.",
          objective: "Detectar outliers LATAM ajustando AVG, MIN y MAX.",
          type: "taller", durationMinutes: 7,
        },
        {
          id: "L3-3",
          title: "GROUP BY",
          summary: "Agrupar resultados LATAM por canal, mercado y vertical.",
          objective: "Segmentar reportes LATAM para decisiones presupuestales.",
          type: "taller", durationMinutes: 7,
        },
        {
          id: "L3-4",
          title: "HAVING",
          summary: "Filtrar segmentos LATAM con metas exigentes usando HAVING.",
          objective: "Identificar clusters LATAM de alto valor con condiciones agregadas.",
          type: "taller", durationMinutes: 7,
        },
      ],
    },
    {
      id: "M4", title: "Funciones",
      summary: "Optimizar campanas LATAM aplicando funciones de fecha, texto y control.",
      lessons: [
        {
          id: "L4-1",
          title: "Funciones DATE",
          summary: "Medir ventanas de conversion LATAM con DATE, DATE_TRUNC y afines.",
          objective: "Analizar cadencia de campanas LATAM usando funciones de fecha.",
          type: "laboratorio", durationMinutes: 7,
        },
        {
          id: "L4-2",
          title: "Funciones STRING",
          summary: "Normalizar UTMs LATAM para reportes limpios y comparables.",
          objective: "Unificar nomenclaturas LATAM usando funciones de texto.",
          type: "laboratorio", durationMinutes: 7,
        },
        {
          id: "L4-3",
          title: "CASE WHEN",
          summary: "Crear segmentos LATAM dinamicos basados en reglas comerciales.",
          objective: "Etiquetar audiencias LATAM aplicando condiciones CASE WHEN.",
          type: "laboratorio", durationMinutes: 7,
        },
        {
          id: "L4-4",
          title: "COALESCE y NULLIF",
          summary: "Gestionar datos incompletos LATAM con COALESCE y NULLIF.",
          objective: "Evitar quiebres en reportes LATAM por valores nulos.",
          type: "laboratorio", durationMinutes: 7,
        },
      ],
    },
    {
      id: "M5", title: "Subconsultas",
      summary: "Aprovechar subconsultas para profundizar segmentaciones LATAM.",
      lessons: [
        {
          id: "L5-1",
          title: "Subquery en WHERE",
          summary: "Detectar clientes LATAM activos con subconsultas en filtros.",
          objective: "Refinar audiencias LATAM usando subconsultas en WHERE.",
          type: "proyecto", durationMinutes: 7,
        },
        {
          id: "L5-2",
          title: "Subquery en FROM",
          summary: "Construir vistas temporales LATAM que consoliden metricas clave.",
          objective: "Combinar metricas LATAM con subconsultas reutilizables en FROM.",
          type: "proyecto", durationMinutes: 7,
        },
        {
          id: "L5-3",
          title: "EXISTS y NOT EXISTS",
          summary: "Priorizar oportunidades LATAM sin seguimiento usando EXISTS.",
          objective: "Automatizar alertas LATAM con subconsultas EXISTS y NOT EXISTS.",
          type: "proyecto", durationMinutes: 7,
        },
      ],
    },
    {
      id: "M6", title: "Window Functions",
      summary: "Aplicar window functions para cohortes y rankings LATAM competitivos.",
      lessons: [
        {
          id: "L6-1",
          title: "ROW_NUMBER y RANK",
          summary: "Ranking LATAM por valor de cliente y frecuencia de compra.",
          objective: "Priorizar cuentas LATAM con ROW_NUMBER y RANK.",
          type: "reto", durationMinutes: 7,
        },
        {
          id: "L6-2",
          title: "PARTITION BY",
          summary: "Evaluar KPIs LATAM por pais, canal y vertical usando PARTITION BY.",
          objective: "Comparar cohorts LATAM con particiones consistentes.",
          type: "reto", durationMinutes: 7,
        },
        {
          id: "L6-3",
          title: "LAG y LEAD",
          summary: "Analizar tendencias LATAM con LAG y LEAD en pipelines.",
          objective: "Anticipar caidas LATAM monitoreando variaciones periodo a periodo.",
          type: "reto", durationMinutes: 7,
        },
      ],
    },
  ],
};
