import 'dart:async';
import 'package:flutter/foundation.dart' show kReleaseMode;
import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';

import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:edaptia/l10n/app_localizations.dart';

import 'package:edaptia/core/app_colors.dart';
import 'package:edaptia/core/router.dart' as app;
import 'package:edaptia/services/progress_service.dart';

// Generated by `flutterfire configure`
import 'firebase_options.dart';

Future<void> _bootstrap() async {
  WidgetsFlutterBinding.ensureInitialized();

  await _loadEnv();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FlutterError.onError = (FlutterErrorDetails details) {
    FirebaseCrashlytics.instance.recordFlutterError(details);
    FlutterError.presentError(details);
  };

  await ProgressService().init();
}

void main() {
  runZonedGuarded(
    () async {
      await _bootstrap();
      runApp(const AelionApp());
    },
    (error, stack) async {
      try {
        await FirebaseCrashlytics.instance
            .recordError(error, stack, fatal: true);
      } catch (_) {
        debugPrint('[runZonedGuarded] Crashlytics recordError failed: $error');
      }
      debugPrint('[runZonedGuarded] Uncaught error: $error\n$stack');
    },
  );
}

Future<void> _loadEnv() async {
  const assetEnv = 'assets/env/.env.public';

  try {
    await dotenv.load(fileName: assetEnv);
  } catch (_) {
    if (!kReleaseMode) {
      try {
        await dotenv.load(fileName: '.env');
      } catch (_) {}
    }
  }

  if (!kReleaseMode) {
    final apiBase =
        dotenv.env['API_BASE_URL'] ?? dotenv.env['BASE_URL'] ?? 'NULL';
    debugPrint('[Aelion][env] API_BASE_URL=$apiBase');
  }
}

class AelionApp extends StatelessWidget {
  const AelionApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      onGenerateTitle: (context) => AppLocalizations.of(context)!.appTitle,
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: const ColorScheme(
          brightness: Brightness.light,
          primary: AppColors.primary,
          onPrimary: AppColors.onPrimary,
          secondary: AppColors.secondary,
          onSecondary: AppColors.onSecondary,
          error: AppColors.error,
          onError: Colors.white,
          surface: AppColors.surface,
          onSurface: AppColors.onSurface,
        ),
        scaffoldBackgroundColor: AppColors.background,
        appBarTheme: const AppBarTheme(
          backgroundColor: AppColors.secondary,
          foregroundColor: AppColors.onSecondary,
          centerTitle: true,
          elevation: 0,
        ),
        textTheme: const TextTheme(
          headlineLarge: TextStyle(fontSize: 28, fontWeight: FontWeight.w800),
          headlineMedium: TextStyle(fontSize: 22, fontWeight: FontWeight.w700),
          titleMedium: TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
          bodyLarge: TextStyle(fontSize: 16, height: 1.35),
          bodyMedium: TextStyle(fontSize: 14, height: 1.35),
          labelLarge: TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
        ).apply(
          bodyColor: AppColors.onSurface,
          displayColor: AppColors.onSurface,
        ),
      ),
      supportedLocales: const [Locale('en'), Locale('es')],
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      onGenerateRoute: (settings) => app.AppRouter.onGenerateRoute(settings),
      onUnknownRoute: (settings) => app.AppRouter.onUnknownRoute(settings),
      initialRoute: '/',
    );
  }
}
