import 'dart:async';
import 'package:flutter/foundation.dart' show kReleaseMode;
import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_phoenix/flutter_phoenix.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';

import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:edaptia/l10n/app_localizations.dart';

import 'package:edaptia/core/app_colors.dart';
import 'package:edaptia/core/design_system/typography.dart';
import 'package:edaptia/core/router.dart' as app;
import 'package:edaptia/services/language_preferences.dart';
import 'package:edaptia/services/progress_service.dart';

// Generated by `flutterfire configure`
import 'firebase_options.dart';

Future<void> _bootstrap() async {
  WidgetsFlutterBinding.ensureInitialized();

  await _loadEnv();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FlutterError.onError = (FlutterErrorDetails details) {
    FirebaseCrashlytics.instance.recordFlutterError(details);
    FlutterError.presentError(details);
  };

  await ProgressService().init();
}

void main() {
  runZonedGuarded(
    () async {
      await _bootstrap();
      runApp(
        Phoenix(
          child: const ProviderScope(
            child: EdaptiaApp(),
          ),
        ),
      );
    },
    (error, stack) async {
      try {
        await FirebaseCrashlytics.instance
            .recordError(error, stack, fatal: true);
      } catch (_) {
        debugPrint('[runZonedGuarded] Crashlytics recordError failed: $error');
      }
      debugPrint('[runZonedGuarded] Uncaught error: $error\n$stack');
    },
  );
}

Future<void> _loadEnv() async {
  const assetEnv = 'assets/env/.env.public';

  try {
    await dotenv.load(fileName: assetEnv);
  } catch (_) {
    if (!kReleaseMode) {
      try {
        await dotenv.load(fileName: '.env');
      } catch (_) {}
    }
  }

  if (!kReleaseMode) {
    final apiBase =
        dotenv.env['API_BASE_URL'] ?? dotenv.env['BASE_URL'] ?? 'NULL';
    debugPrint('[Edaptia][env] API_BASE_URL=$apiBase');
  }
}

class EdaptiaApp extends StatefulWidget {
  const EdaptiaApp({super.key});

  @override
  State<EdaptiaApp> createState() => _EdaptiaAppState();
}

class _EdaptiaAppState extends State<EdaptiaApp> {
  Locale? _preferredLocale;

  @override
  void initState() {
    super.initState();
    _loadPreferredLocale();
  }

  Future<void> _loadPreferredLocale() async {
    final code = await LanguagePreferences.getPreferredLanguageCode();
    if (!mounted) return;
    final locale = LanguagePreferences.resolveLocale(code);
    if (locale == null) return;
    setState(() => _preferredLocale = locale);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      locale: _preferredLocale,
      onGenerateTitle: (context) => AppLocalizations.of(context)!.appTitle,
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: const ColorScheme(
          brightness: Brightness.light,
          primary: AppColors.primary,
          onPrimary: AppColors.onPrimary,
          secondary: AppColors.secondary,
          onSecondary: AppColors.onSecondary,
          error: AppColors.error,
          onError: Colors.white,
          surface: AppColors.surface,
          onSurface: AppColors.onSurface,
        ),
        scaffoldBackgroundColor: AppColors.background,
        appBarTheme: const AppBarTheme(
          backgroundColor: AppColors.primary,
          foregroundColor: AppColors.onPrimary,
          centerTitle: true,
          elevation: 0,
        ),
        textTheme: TextTheme(
          headlineLarge: EdaptiaTypography.largeTitle,
          headlineMedium: EdaptiaTypography.title1,
          headlineSmall: EdaptiaTypography.title2,
          titleLarge: EdaptiaTypography.title2,
          titleMedium: EdaptiaTypography.title3,
          bodyLarge: EdaptiaTypography.body,
          bodyMedium: EdaptiaTypography.callout,
          bodySmall: EdaptiaTypography.subheadline,
          labelLarge: EdaptiaTypography.bodyBold,
          labelSmall: EdaptiaTypography.caption,
        ).apply(
          bodyColor: AppColors.onSurface,
          displayColor: AppColors.onSurface,
        ),
      ),
      supportedLocales: const [Locale('en'), Locale('es')],
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      onGenerateRoute: (settings) => app.AppRouter.onGenerateRoute(settings),
      onUnknownRoute: (settings) => app.AppRouter.onUnknownRoute(settings),
      initialRoute: '/',
    );
  }
}

